#include "store/store-owners.h"
#include "store/store-util.h"
#include "player/player-race-types.h"

/*!
 * @todo _() でまとめる
 */
const owner_type owners[MAX_STORES][MAX_OWNERS] = { {
/* General store - 32 unique names */
/*
  Raistlin は dragonlance の powerful wizard 。
  Rincewind the Chicken は Terry Pratchett の Discworld の登場人物 上記のパロディ？、
  { "憶病者ラストリン",  200, 108, player_player_race_type::type::HUMAN},
  { "Raistlin the Chicken", 200, 108, player_player_race_type::type::HUMAN},
*/
#ifdef JP
                                                        { "フレンドリーなビルボ", 30000, 108, player_race_type::HOBBIT, STORE_OBJ_STD_LEVEL },
                                                        { "憶病者リンスウィンド", 30000, 108, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
                                                        { "背の低いサルタン", 30000, 107, player_race_type::GNOME, STORE_OBJ_STD_LEVEL },
                                                        { "ハンサムなライア=エル", 30000, 107, player_race_type::ELF, STORE_OBJ_STD_LEVEL },
                                                        { "親切なファリルマウエン", 30000, 108, player_race_type::HOBBIT, STORE_OBJ_STD_LEVEL },
                                                        { "臆病者ヴォワラン", 30000, 108, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
                                                        { "チビのエラシュナク", 30000, 107, player_race_type::BEASTMAN, STORE_OBJ_STD_LEVEL },
                                                        { "ハンサムなグラッグ", 30000, 107, player_race_type::HALF_TITAN, STORE_OBJ_STD_LEVEL },
                                                        { "ケチなフォロビア", 30000, 108, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
                                                        { "馬鹿のエリス", 30000, 108, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
                                                        { "腹ペコのフィルバート", 30000, 107, player_race_type::VAMPIRE, STORE_OBJ_STD_LEVEL },
                                                        { "スナーグル・サシグア", 30000, 107, player_race_type::MIND_FLAYER, STORE_OBJ_STD_LEVEL },
                                                        { "長死きエロワーズ", 30000, 108, player_race_type::SPECTRE, STORE_OBJ_STD_LEVEL },
                                                        { "ノロマのフンディ", 30000, 108, player_race_type::ZOMBIE, STORE_OBJ_STD_LEVEL },
                                                        { "グランサス", 30000, 107, player_race_type::SKELETON, STORE_OBJ_STD_LEVEL },
                                                        { "丁寧なロラックス", 30000, 107, player_race_type::VAMPIRE, STORE_OBJ_STD_LEVEL },
                                                        { "ブッチ", 30000, 108, player_race_type::HALF_ORC, STORE_OBJ_STD_LEVEL },
                                                        { "美しきエルベレス", 30000, 108, player_race_type::HIGH_ELF, STORE_OBJ_STD_LEVEL },
                                                        { "こそこそサーレス", 30000, 107, player_race_type::GNOME, STORE_OBJ_STD_LEVEL },
                                                        { "ナーロック", 30000, 107, player_race_type::DWARF, STORE_OBJ_STD_LEVEL },
                                                        { "チビのヘイネッカ", 30000, 108, player_race_type::GNOME, STORE_OBJ_STD_LEVEL },
                                                        { "きちがいロワラン", 30000, 108, player_race_type::HALF_GIANT, STORE_OBJ_STD_LEVEL },
                                                        { "毒息のウート", 30000, 107, player_race_type::DRACONIAN, STORE_OBJ_STD_LEVEL },
                                                        { "でぶっちょアラァカ", 30000, 107, player_race_type::DRACONIAN, STORE_OBJ_STD_LEVEL },
                                                        { "低能なプーゴー", 30000, 108, player_race_type::BEASTMAN, STORE_OBJ_STD_LEVEL },
                                                        { "フェロールフィリアン", 30000, 108, player_race_type::ELF, STORE_OBJ_STD_LEVEL },
                                                        { "年寄りマロカ", 30000, 107, player_race_type::GNOME, STORE_OBJ_STD_LEVEL },
                                                        { "勇敢なサシン", 30000, 107, player_race_type::HALF_GIANT, STORE_OBJ_STD_LEVEL },
                                                        { "田舎者アビエマール", 30000, 108, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
                                                        { "貧乏なハーク", 30000, 108, player_race_type::HALF_ORC, STORE_OBJ_STD_LEVEL },
                                                        { "みじめなソアリン", 30000, 107, player_race_type::ZOMBIE, STORE_OBJ_STD_LEVEL },
                                                        { "質素なメルラ", 30000, 107, player_race_type::ELF, STORE_OBJ_STD_LEVEL },
#else
                                                        { "Bilbo the Friendly", 30000, 108, player_race_type::HOBBIT, STORE_OBJ_STD_LEVEL },
                                                        { "Rincewind the Chicken", 30000, 108, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
                                                        { "Sultan the Midget", 30000, 107, player_race_type::GNOME, STORE_OBJ_STD_LEVEL },
                                                        { "Lyar-el the Comely", 30000, 107, player_race_type::ELF, STORE_OBJ_STD_LEVEL },
                                                        { "Falilmawen the Friendly", 30000, 108, player_race_type::HOBBIT, STORE_OBJ_STD_LEVEL },
                                                        { "Voirin the Cowardly", 30000, 108, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
                                                        { "Erashnak the Midget", 30000, 107, player_race_type::BEASTMAN, STORE_OBJ_STD_LEVEL },
                                                        { "Grug the Comely", 30000, 107, player_race_type::HALF_TITAN, STORE_OBJ_STD_LEVEL },
                                                        { "Forovir the Cheap", 30000, 108, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
                                                        { "Ellis the Fool", 30000, 108, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
                                                        { "Filbert the Hungry", 30000, 107, player_race_type::VAMPIRE, STORE_OBJ_STD_LEVEL },
                                                        { "Fthnargl Psathiggua", 30000, 107, player_race_type::MIND_FLAYER, STORE_OBJ_STD_LEVEL },
                                                        { "Eloise Long-Dead", 30000, 108, player_race_type::SPECTRE, STORE_OBJ_STD_LEVEL },
                                                        { "Fundi the Slow", 30000, 108, player_race_type::ZOMBIE, STORE_OBJ_STD_LEVEL },
                                                        { "Granthus", 30000, 107, player_race_type::SKELETON, STORE_OBJ_STD_LEVEL },
                                                        { "Lorax the Suave", 30000, 107, player_race_type::VAMPIRE, STORE_OBJ_STD_LEVEL },
                                                        { "Butch", 30000, 108, player_race_type::HALF_ORC, STORE_OBJ_STD_LEVEL },
                                                        { "Elbereth the Beautiful", 30000, 108, player_race_type::HIGH_ELF, STORE_OBJ_STD_LEVEL },
                                                        { "Sarleth the Sneaky", 30000, 107, player_race_type::GNOME, STORE_OBJ_STD_LEVEL },
                                                        { "Narlock", 30000, 107, player_race_type::DWARF, STORE_OBJ_STD_LEVEL },
                                                        { "Haneka the Small", 30000, 108, player_race_type::GNOME, STORE_OBJ_STD_LEVEL },
                                                        { "Loirin the Mad", 30000, 108, player_race_type::HALF_GIANT, STORE_OBJ_STD_LEVEL },
                                                        { "Wuto Poisonbreath", 30000, 107, player_race_type::DRACONIAN, STORE_OBJ_STD_LEVEL },
                                                        { "Araaka the Rotund", 30000, 107, player_race_type::DRACONIAN, STORE_OBJ_STD_LEVEL },
                                                        { "Poogor the Dumb", 30000, 108, player_race_type::BEASTMAN, STORE_OBJ_STD_LEVEL },
                                                        { "Felorfiliand", 30000, 108, player_race_type::ELF, STORE_OBJ_STD_LEVEL },
                                                        { "Maroka the Aged", 30000, 107, player_race_type::GNOME, STORE_OBJ_STD_LEVEL },
                                                        { "Sasin the Bold", 30000, 107, player_race_type::HALF_GIANT, STORE_OBJ_STD_LEVEL },
                                                        { "Abiemar the Peasant", 30000, 108, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
                                                        { "Hurk the Poor", 30000, 108, player_race_type::HALF_ORC, STORE_OBJ_STD_LEVEL },
                                                        { "Soalin the Wretched", 30000, 107, player_race_type::ZOMBIE, STORE_OBJ_STD_LEVEL },
                                                        { "Merulla the Humble", 30000, 107, player_race_type::ELF, STORE_OBJ_STD_LEVEL },
#endif
                                                    },
    {
/* Armoury - 28 unique names */
#ifdef JP
        { "醜悪コン=ダー", 30000, 115, player_race_type::HALF_ORC, STORE_OBJ_STD_LEVEL },
        { "頑固者ダーグ=ロウ", 30000, 111, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "賢者デカド", 30000, 112, player_race_type::DUNADAN, STORE_OBJ_STD_LEVEL },
        { "鍛冶屋のウィーランド", 30000, 112, player_race_type::DWARF, STORE_OBJ_STD_LEVEL },
        { "醜悪コン=ダー", 30000, 115, player_race_type::HALF_ORC, STORE_OBJ_STD_LEVEL },
        { "頑固者ダーグ=ロウ", 30000, 111, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "ハンサムなデカド", 30000, 112, player_race_type::AMBERITE, STORE_OBJ_STD_LEVEL },
        { "エロー・ドラゴンスケイル", 30000, 112, player_race_type::ELF, STORE_OBJ_STD_LEVEL },
        { "デリカトス", 30000, 115, player_race_type::SPRITE, STORE_OBJ_STD_LEVEL },
        { "巨大なグルース", 30000, 111, player_race_type::HALF_GIANT, STORE_OBJ_STD_LEVEL },
        { "アニムス", 30000, 112, player_race_type::GOLEM, STORE_OBJ_STD_LEVEL },
        { "マルヴァス", 30000, 112, player_race_type::HALF_TITAN, STORE_OBJ_STD_LEVEL },
        { "セラクシス", 30000, 115, player_race_type::ZOMBIE, STORE_OBJ_STD_LEVEL },
        { "デス・チル", 30000, 111, player_race_type::SPECTRE, STORE_OBJ_STD_LEVEL },
        { "微かなドリオス", 30000, 112, player_race_type::SPECTRE, STORE_OBJ_STD_LEVEL },
        { "冷たいバスリック", 30000, 112, player_race_type::VAMPIRE, STORE_OBJ_STD_LEVEL },
        { "冷酷ヴェンジェラ", 30000, 115, player_race_type::HALF_TROLL, STORE_OBJ_STD_LEVEL },
        { "強者ウィラナ", 30000, 111, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "ヨジョ二世", 30000, 112, player_race_type::DWARF, STORE_OBJ_STD_LEVEL },
        { "優しいラナラー", 30000, 112, player_race_type::AMBERITE, STORE_OBJ_STD_LEVEL },
        { "不浄のホルバグ", 30000, 115, player_race_type::HALF_ORC, STORE_OBJ_STD_LEVEL },
        { "テレパスのエレレン", 30000, 111, player_race_type::DARK_ELF, STORE_OBJ_STD_LEVEL },
        { "イスドリリアス", 30000, 112, player_race_type::SPRITE, STORE_OBJ_STD_LEVEL },
        { "一つ目ヴェグナー", 30000, 112, player_race_type::CYCLOPS, STORE_OBJ_STD_LEVEL },
        { "混沌のロディッシュ", 30000, 115, player_race_type::BEASTMAN, STORE_OBJ_STD_LEVEL },
        { "剣豪ヘジン", 30000, 111, player_race_type::NIBELUNG, STORE_OBJ_STD_LEVEL },
        { "ずる屋のエルベレリス", 30000, 112, player_race_type::DARK_ELF, STORE_OBJ_STD_LEVEL },
        { "インプのザサス", 30000, 112, player_race_type::IMP, STORE_OBJ_STD_LEVEL },
        { "醜悪コン=ダー", 30000, 115, player_race_type::HALF_ORC, STORE_OBJ_STD_LEVEL },
        { "頑固者ダーグ=ロウ", 30000, 111, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "ハンサムなデカド", 30000, 112, player_race_type::AMBERITE, STORE_OBJ_STD_LEVEL },
        { "鍛冶屋のウィーランド", 30000, 112, player_race_type::DWARF, STORE_OBJ_STD_LEVEL },
#else
        { "Kon-Dar the Ugly", 30000, 115, player_race_type::HALF_ORC, STORE_OBJ_STD_LEVEL },
        { "Darg-Low the Grim", 30000, 111, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "Decado the Handsome", 30000, 112, player_race_type::DUNADAN, STORE_OBJ_STD_LEVEL },
        { "Wieland the Smith", 30000, 112, player_race_type::DWARF, STORE_OBJ_STD_LEVEL },
        { "Kon-Dar the Ugly", 30000, 115, player_race_type::HALF_ORC, STORE_OBJ_STD_LEVEL },
        { "Darg-Low the Grim", 30000, 111, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "Decado the Handsome", 30000, 112, player_race_type::AMBERITE, STORE_OBJ_STD_LEVEL },
        { "Elo Dragonscale", 30000, 112, player_race_type::ELF, STORE_OBJ_STD_LEVEL },
        { "Delicatus", 30000, 115, player_race_type::SPRITE, STORE_OBJ_STD_LEVEL },
        { "Gruce the Huge", 30000, 111, player_race_type::HALF_GIANT, STORE_OBJ_STD_LEVEL },
        { "Animus", 30000, 112, player_race_type::GOLEM, STORE_OBJ_STD_LEVEL },
        { "Malvus", 30000, 112, player_race_type::HALF_TITAN, STORE_OBJ_STD_LEVEL },
        { "Selaxis", 30000, 115, player_race_type::ZOMBIE, STORE_OBJ_STD_LEVEL },
        { "Deathchill", 30000, 111, player_race_type::SPECTRE, STORE_OBJ_STD_LEVEL },
        { "Drios the Faint", 30000, 112, player_race_type::SPECTRE, STORE_OBJ_STD_LEVEL },
        { "Bathric the Cold", 30000, 112, player_race_type::VAMPIRE, STORE_OBJ_STD_LEVEL },
        { "Vengella the Cruel", 30000, 115, player_race_type::HALF_TROLL, STORE_OBJ_STD_LEVEL },
        { "Wyrana the Mighty", 30000, 111, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "Yojo II", 30000, 112, player_race_type::DWARF, STORE_OBJ_STD_LEVEL },
        { "Ranalar the Sweet", 30000, 112, player_race_type::AMBERITE, STORE_OBJ_STD_LEVEL },
        { "Horbag the Unclean", 30000, 115, player_race_type::HALF_ORC, STORE_OBJ_STD_LEVEL },
        { "Elelen the Telepath", 30000, 111, player_race_type::DARK_ELF, STORE_OBJ_STD_LEVEL },
        { "Isedrelias", 30000, 112, player_race_type::SPRITE, STORE_OBJ_STD_LEVEL },
        { "Vegnar One-eye", 30000, 112, player_race_type::CYCLOPS, STORE_OBJ_STD_LEVEL },
        { "Rodish the Chaotic", 30000, 115, player_race_type::BEASTMAN, STORE_OBJ_STD_LEVEL },
        { "Hesin Swordmaster", 30000, 111, player_race_type::NIBELUNG, STORE_OBJ_STD_LEVEL },
        { "Elvererith the Cheat", 30000, 112, player_race_type::DARK_ELF, STORE_OBJ_STD_LEVEL },
        { "Zzathath the Imp", 30000, 112, player_race_type::IMP, STORE_OBJ_STD_LEVEL },
        { "Kon-Dar the Ugly", 30000, 115, player_race_type::HALF_ORC, STORE_OBJ_STD_LEVEL },
        { "Darg-Low the Grim", 30000, 111, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "Decado the Handsome", 30000, 112, player_race_type::AMBERITE, STORE_OBJ_STD_LEVEL },
        { "Wieland the Smith", 30000, 112, player_race_type::DWARF, STORE_OBJ_STD_LEVEL },
#endif
    },

    {
/* Weapon Smith - 28 unique names */
#ifdef JP
        { "残忍なるアーノルド", 30000, 115, player_race_type::HALF_TROLL, STORE_OBJ_STD_LEVEL },
        { "獣殺しのアーンダル", 30000, 110, player_race_type::HALF_ELF, STORE_OBJ_STD_LEVEL },
        { "獣マスターのエディー", 30000, 115, player_race_type::HOBBIT, STORE_OBJ_STD_LEVEL },
        { "竜殺しのオグライン", 30000, 112, player_race_type::DWARF, STORE_OBJ_STD_LEVEL },
        { "熟練者ドリュー", 30000, 115, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "龍の子オラックス", 30000, 110, player_race_type::DRACONIAN, STORE_OBJ_STD_LEVEL },
        { "病気持ちのアンスラックス", 30000, 115, player_race_type::BEASTMAN, STORE_OBJ_STD_LEVEL },
        { "頑丈者アルコス", 30000, 112, player_race_type::DWARF, STORE_OBJ_STD_LEVEL },
        { "腐れ者のサリアス", 30000, 115, player_race_type::ZOMBIE, STORE_OBJ_STD_LEVEL },
        { "晒し骨のトゥエシク", 30000, 110, player_race_type::SKELETON, STORE_OBJ_STD_LEVEL },
        { "ビリオス", 30000, 115, player_race_type::BEASTMAN, STORE_OBJ_STD_LEVEL },
        { "ファスガル", 30000, 112, player_race_type::ZOMBIE, STORE_OBJ_STD_LEVEL },
        { "パラディンのエレフリス", 30000, 115, player_race_type::BARBARIAN, STORE_OBJ_STD_LEVEL },
        { "キ'トリッ'ク", 30000, 110, player_race_type::KLACKON, STORE_OBJ_STD_LEVEL },
        { "蜘蛛の友ドゥロカス", 30000, 115, player_race_type::DARK_ELF, STORE_OBJ_STD_LEVEL },
        { "巨人殺しのフングス", 30000, 112, player_race_type::DWARF, STORE_OBJ_STD_LEVEL },
        { "デランサ", 30000, 115, player_race_type::ELF, STORE_OBJ_STD_LEVEL },
        { "レンジャーのソルビスタニ", 30000, 110, player_race_type::HALF_ELF, STORE_OBJ_STD_LEVEL },
        { "ノロマのゾリル", 30000, 115, player_race_type::GOLEM, STORE_OBJ_STD_LEVEL },
        { "イーオン・フラックス", 30000, 112, player_race_type::HALF_ELF, STORE_OBJ_STD_LEVEL },
        { "強者ナドック", 30000, 115, player_race_type::HOBBIT, STORE_OBJ_STD_LEVEL },
        { "弱虫エラモグ", 30000, 110, player_race_type::KOBOLD, STORE_OBJ_STD_LEVEL },
        { "公正なエオウィリス", 30000, 115, player_race_type::VAMPIRE, STORE_OBJ_STD_LEVEL },
        { "バルログ殺しのヒュイモグ", 30000, 112, player_race_type::HALF_ORC, STORE_OBJ_STD_LEVEL },
        { "冷酷ピーダス", 30000, 115, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "ヴァモグ スレイヤー", 30000, 110, player_race_type::HALF_OGRE, STORE_OBJ_STD_LEVEL },
        { "性悪フーシュナク", 30000, 115, player_race_type::BEASTMAN, STORE_OBJ_STD_LEVEL },
        { "舞闘バレン", 30000, 112, player_race_type::BARBARIAN, STORE_OBJ_STD_LEVEL },
        { "残忍なるアーノルド", 30000, 115, player_race_type::BARBARIAN, STORE_OBJ_STD_LEVEL },
        { "獣殺しのアーンダル", 30000, 110, player_race_type::HALF_ELF, STORE_OBJ_STD_LEVEL },
        { "ビーストマスター・エディー", 30000, 115, player_race_type::HALF_ORC, STORE_OBJ_STD_LEVEL },
        { "竜殺しのオグライン", 30000, 112, player_race_type::DWARF, STORE_OBJ_STD_LEVEL },
#else
        { "Arnold the Beastly", 30000, 115, player_race_type::BARBARIAN, STORE_OBJ_STD_LEVEL },
        { "Arndal Beast-Slayer", 30000, 110, player_race_type::HALF_ELF, STORE_OBJ_STD_LEVEL },
        { "Eddie Beast-Master", 30000, 115, player_race_type::HALF_ORC, STORE_OBJ_STD_LEVEL },
        { "Oglign Dragon-Slayer", 30000, 112, player_race_type::DWARF, STORE_OBJ_STD_LEVEL },
        { "Drew the Skilled", 30000, 115, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "Orrax Dragonson", 30000, 110, player_race_type::DRACONIAN, STORE_OBJ_STD_LEVEL },
        { "Anthrax Disease-Carrier", 30000, 115, player_race_type::BEASTMAN, STORE_OBJ_STD_LEVEL },
        { "Arkhoth the Stout", 30000, 112, player_race_type::DWARF, STORE_OBJ_STD_LEVEL },
        { "Sarlyas the Rotten", 30000, 115, player_race_type::ZOMBIE, STORE_OBJ_STD_LEVEL },
        { "Tuethic Bare-Bones", 30000, 110, player_race_type::SKELETON, STORE_OBJ_STD_LEVEL },
        { "Bilious", 30000, 115, player_race_type::BEASTMAN, STORE_OBJ_STD_LEVEL },
        { "Fasgul", 30000, 112, player_race_type::ZOMBIE, STORE_OBJ_STD_LEVEL },
        { "Ellefris the Paladin", 30000, 115, player_race_type::BARBARIAN, STORE_OBJ_STD_LEVEL },
        { "K'trrik'k", 30000, 110, player_race_type::KLACKON, STORE_OBJ_STD_LEVEL },
        { "Drocus Spiderfriend", 30000, 115, player_race_type::DARK_ELF, STORE_OBJ_STD_LEVEL },
        { "Fungus Giant-Slayer", 30000, 112, player_race_type::DWARF, STORE_OBJ_STD_LEVEL },
        { "Delantha", 30000, 115, player_race_type::ELF, STORE_OBJ_STD_LEVEL },
        { "Solvistani the Ranger", 30000, 110, player_race_type::HALF_ELF, STORE_OBJ_STD_LEVEL },
        { "Xoril the Slow", 30000, 115, player_race_type::GOLEM, STORE_OBJ_STD_LEVEL },
        { "Aeon Flux", 30000, 112, player_race_type::HALF_ELF, STORE_OBJ_STD_LEVEL },
        { "Nadoc the Strong", 30000, 115, player_race_type::HOBBIT, STORE_OBJ_STD_LEVEL },
        { "Eramog the Weak", 30000, 110, player_race_type::KOBOLD, STORE_OBJ_STD_LEVEL },
        { "Eowilith the Fair", 30000, 115, player_race_type::VAMPIRE, STORE_OBJ_STD_LEVEL },
        { "Huimog Balrog-Slayer", 30000, 112, player_race_type::HALF_ORC, STORE_OBJ_STD_LEVEL },
        { "Peadus the Cruel", 30000, 115, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "Vamog Slayer", 30000, 110, player_race_type::HALF_OGRE, STORE_OBJ_STD_LEVEL },
        { "Hooshnak the Vicious", 30000, 115, player_race_type::BEASTMAN, STORE_OBJ_STD_LEVEL },
        { "Balenn War-Dancer", 30000, 112, player_race_type::BARBARIAN, STORE_OBJ_STD_LEVEL },
        { "Arnold the Beastly", 30000, 115, player_race_type::BARBARIAN, STORE_OBJ_STD_LEVEL },
        { "Arndal Beast-Slayer", 30000, 110, player_race_type::HALF_ELF, STORE_OBJ_STD_LEVEL },
        { "Eddie Beast-Master", 30000, 115, player_race_type::HALF_ORC, STORE_OBJ_STD_LEVEL },
        { "Oglign Dragon-Slayer", 30000, 112, player_race_type::DWARF, STORE_OBJ_STD_LEVEL },
#endif
    },
    {
/* Temple - 22 unique names */
#ifdef JP
        { "質素なルードヴィヒ", 30000, 109, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "パラディンのガンナー", 30000, 110, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "選ばれしトリン", 30000, 107, player_race_type::ELF, STORE_OBJ_STD_LEVEL },
        { "賢明なるサラストロ", 30000, 109, player_race_type::DWARF, STORE_OBJ_STD_LEVEL },
        { "パーシヴァル卿", 30000, 107, player_race_type::HIGH_ELF, STORE_OBJ_STD_LEVEL },
        { "神聖なるアセナス", 30000, 109, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "マッキノン", 30000, 109, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "謹み婦人", 30000, 110, player_race_type::HIGH_ELF, STORE_OBJ_STD_LEVEL },
        { "ドルイドのハシュニック", 30000, 107, player_race_type::HOBBIT, STORE_OBJ_STD_LEVEL },
        { "フィナク", 30000, 109, player_race_type::YEEK, STORE_OBJ_STD_LEVEL },
        { "クリキック", 30000, 109, player_race_type::KLACKON, STORE_OBJ_STD_LEVEL },
        { "荒くれ者モリヴァル", 30000, 110, player_race_type::ELF, STORE_OBJ_STD_LEVEL },
        { "暗きホシャック", 30000, 107, player_race_type::IMP, STORE_OBJ_STD_LEVEL },
        { "賢者アタール", 30000, 109, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "清きイベニッド", 30000, 109, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "エリディシュ", 30000, 110, player_race_type::HALF_TROLL, STORE_OBJ_STD_LEVEL },
        { "呪術師ヴルドゥシュ", 30000, 107, player_race_type::HALF_OGRE, STORE_OBJ_STD_LEVEL },
        { "狂戦士ハオブ", 30000, 109, player_race_type::BARBARIAN, STORE_OBJ_STD_LEVEL },
        { "若きプルーグディシュ", 30000, 109, player_race_type::HALF_OGRE, STORE_OBJ_STD_LEVEL },
        { "きちがいラムワイズ", 30000, 110, player_race_type::YEEK, STORE_OBJ_STD_LEVEL },
        { "有徳者ムワート", 30000, 107, player_race_type::KOBOLD, STORE_OBJ_STD_LEVEL },
        { "弱虫ダードバード", 30000, 109, player_race_type::SPECTRE, STORE_OBJ_STD_LEVEL },
        { "質素なルードヴィヒ", 30000, 109, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "パラディンのガンナー", 30000, 110, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "選ばれしトリン", 30000, 107, player_race_type::ELF, STORE_OBJ_STD_LEVEL },
        { "賢明なるサラストロ", 30000, 109, player_race_type::DWARF, STORE_OBJ_STD_LEVEL },
        { "パーシヴァル卿", 30000, 107, player_race_type::HIGH_ELF, STORE_OBJ_STD_LEVEL },
        { "神聖なるアセナス", 30000, 109, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "マッキノン", 30000, 109, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "謹み婦人", 30000, 110, player_race_type::HIGH_ELF, STORE_OBJ_STD_LEVEL },
        { "ドルイドのハシュニック", 30000, 107, player_race_type::HOBBIT, STORE_OBJ_STD_LEVEL },
        { "フィナク", 30000, 109, player_race_type::YEEK, STORE_OBJ_STD_LEVEL },
#else
        { "Ludwig the Humble", 30000, 109, player_race_type::DWARF, STORE_OBJ_STD_LEVEL },
        { "Gunnar the Paladin", 30000, 110, player_race_type::HALF_TROLL, STORE_OBJ_STD_LEVEL },
        { "Torin the Chosen", 30000, 107, player_race_type::HIGH_ELF, STORE_OBJ_STD_LEVEL },
        { "Sarastro the Wise", 30000, 109, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "Sir Parsival the Pure", 30000, 107, player_race_type::HIGH_ELF, STORE_OBJ_STD_LEVEL },
        { "Asenath the Holy", 30000, 109, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "McKinnon", 30000, 109, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "Mistress Chastity", 30000, 110, player_race_type::HIGH_ELF, STORE_OBJ_STD_LEVEL },
        { "Hashnik the Druid", 30000, 107, player_race_type::HOBBIT, STORE_OBJ_STD_LEVEL },
        { "Finak", 30000, 109, player_race_type::YEEK, STORE_OBJ_STD_LEVEL },
        { "Krikkik", 30000, 109, player_race_type::KLACKON, STORE_OBJ_STD_LEVEL },
        { "Morival the Wild", 30000, 110, player_race_type::ELF, STORE_OBJ_STD_LEVEL },
        { "Hoshak the Dark", 30000, 107, player_race_type::IMP, STORE_OBJ_STD_LEVEL },
        { "Atal the Wise", 30000, 109, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "Ibenidd the Chaste", 30000, 109, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "Eridish", 30000, 110, player_race_type::HALF_TROLL, STORE_OBJ_STD_LEVEL },
        { "Vrudush the Shaman", 30000, 107, player_race_type::HALF_OGRE, STORE_OBJ_STD_LEVEL },
        { "Haob the Berserker", 30000, 109, player_race_type::BARBARIAN, STORE_OBJ_STD_LEVEL },
        { "Proogdish the Youthfull", 30000, 109, player_race_type::HALF_OGRE, STORE_OBJ_STD_LEVEL },
        { "Lumwise the Mad", 30000, 110, player_race_type::YEEK, STORE_OBJ_STD_LEVEL },
        { "Muirt the Virtuous", 30000, 107, player_race_type::KOBOLD, STORE_OBJ_STD_LEVEL },
        { "Dardobard the Weak", 30000, 109, player_race_type::SPECTRE, STORE_OBJ_STD_LEVEL },
        { "Ludwig the Humble", 30000, 109, player_race_type::DWARF, STORE_OBJ_STD_LEVEL },
        { "Gunnar the Paladin", 30000, 110, player_race_type::HALF_TROLL, STORE_OBJ_STD_LEVEL },
        { "Torin the Chosen", 30000, 107, player_race_type::HIGH_ELF, STORE_OBJ_STD_LEVEL },
        { "Sarastro the Wise", 30000, 109, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "Sir Parsival the Pure", 30000, 107, player_race_type::HIGH_ELF, STORE_OBJ_STD_LEVEL },
        { "Asenath the Holy", 30000, 109, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "McKinnon", 30000, 109, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "Mistress Chastity", 30000, 110, player_race_type::HIGH_ELF, STORE_OBJ_STD_LEVEL },
        { "Hashnik the Druid", 30000, 107, player_race_type::HOBBIT, STORE_OBJ_STD_LEVEL },
        { "Finak", 30000, 109, player_race_type::YEEK, STORE_OBJ_STD_LEVEL },
#endif
    },
    {
/* Alchemist - 26 unique names */
#ifdef JP
        { "化学者マウザー", 30000, 111, player_race_type::HALF_ELF, STORE_OBJ_STD_LEVEL },
        { "カオスのウィズル", 30000, 110, player_race_type::HOBBIT, STORE_OBJ_STD_LEVEL },
        { "強欲ミダス", 30000, 116, player_race_type::GNOME, STORE_OBJ_STD_LEVEL },
        { "貧弱ジャ=ファー", 30000, 111, player_race_type::ELF }, /*FIRST*/
        { "カカルラカカル", 30000, 116, player_race_type::KLACKON, STORE_OBJ_STD_LEVEL },
        { "錬金術師ジャル=エス", 30000, 111, player_race_type::ELF, STORE_OBJ_STD_LEVEL },
        { "用心深いファネラス", 30000, 111, player_race_type::DWARF, STORE_OBJ_STD_LEVEL },
        { "キチガイのルンシー", 30000, 110, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "グランブルワース", 30000, 116, player_race_type::GNOME, STORE_OBJ_STD_LEVEL },
        { "フリッター", 30000, 111, player_race_type::SPRITE, STORE_OBJ_STD_LEVEL },
        { "ザリルス", 30000, 111, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "古きエグバート", 30000, 110, player_race_type::DWARF, STORE_OBJ_STD_LEVEL },
        { "誇り高きヴァリンドラ", 30000, 116, player_race_type::HIGH_ELF, STORE_OBJ_STD_LEVEL },
        { "錬金術師タエン", 30000, 111, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "巧言カイド", 30000, 111, player_race_type::VAMPIRE, STORE_OBJ_STD_LEVEL },
        { "暗きフリア", 30000, 110, player_race_type::NIBELUNG, STORE_OBJ_STD_LEVEL },
        { "質素なドムリ", 30000, 116, player_race_type::DWARF, STORE_OBJ_STD_LEVEL },
        { "魔の子ヤァジュッカ", 30000, 111, player_race_type::IMP, STORE_OBJ_STD_LEVEL },
        { "薬草師ジェララルドール", 30000, 111, player_race_type::HIGH_ELF, STORE_OBJ_STD_LEVEL },
        { "賢者オレラルダン", 30000, 110, player_race_type::BARBARIAN, STORE_OBJ_STD_LEVEL },
        { "デモニシストのフゾグロ", 30000, 116, player_race_type::IMP, STORE_OBJ_STD_LEVEL },
        { "錬金術師ドゥリアシュ", 30000, 111, player_race_type::HALF_ORC, STORE_OBJ_STD_LEVEL },
        { "強者ネリア", 30000, 111, player_race_type::CYCLOPS, STORE_OBJ_STD_LEVEL },
        { "辛口リグナス", 30000, 110, player_race_type::HALF_ORC, STORE_OBJ_STD_LEVEL },
        { "ティルバ", 30000, 116, player_race_type::HOBBIT, STORE_OBJ_STD_LEVEL },
        { "金持ちミリルドリック", 30000, 111, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },

        { "科学者マウザー", 30000, 111, player_race_type::HALF_ELF, STORE_OBJ_STD_LEVEL },
        { "カオスのウィズル", 30000, 110, player_race_type::HOBBIT, STORE_OBJ_STD_LEVEL },
        { "強欲ミダス", 30000, 116, player_race_type::GNOME, STORE_OBJ_STD_LEVEL },
        { "錬金術師ジャ=ファー", 30000, 111, player_race_type::ELF, STORE_OBJ_STD_LEVEL },
        { "カカルラカカル", 30000, 116, player_race_type::KLACKON, STORE_OBJ_STD_LEVEL },
        { "錬金術師ジャル=エス", 30000, 111, player_race_type::ELF, STORE_OBJ_STD_LEVEL },
#else
        { "Mauser the Chemist", 30000, 111, player_race_type::HALF_ELF, STORE_OBJ_STD_LEVEL },
        { "Wizzle the Chaotic", 30000, 110, player_race_type::HOBBIT, STORE_OBJ_STD_LEVEL },
        { "Midas the Greedy", 30000, 116, player_race_type::GNOME, STORE_OBJ_STD_LEVEL },
        { "Ja-Far the Alchemist", 30000, 111, player_race_type::ELF, STORE_OBJ_STD_LEVEL },
        { "Kakalrakakal", 30000, 116, player_race_type::KLACKON, STORE_OBJ_STD_LEVEL },
        { "Jal-Eth the Alchemist", 30000, 111, player_race_type::ELF, STORE_OBJ_STD_LEVEL },
        { "Fanelath the Cautious", 30000, 111, player_race_type::DWARF, STORE_OBJ_STD_LEVEL },
        { "Runcie the Insane", 30000, 110, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "Grumbleworth", 30000, 116, player_race_type::GNOME, STORE_OBJ_STD_LEVEL },
        { "Flitter", 30000, 111, player_race_type::SPRITE, STORE_OBJ_STD_LEVEL },
        { "Xarillus", 30000, 111, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "Egbert the Old", 30000, 110, player_race_type::DWARF, STORE_OBJ_STD_LEVEL },
        { "Valindra the Proud", 30000, 116, player_race_type::HIGH_ELF, STORE_OBJ_STD_LEVEL },
        { "Taen the Alchemist", 30000, 111, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "Cayd the Sweet", 30000, 111, player_race_type::VAMPIRE, STORE_OBJ_STD_LEVEL },
        { "Fulir the Dark", 30000, 110, player_race_type::NIBELUNG, STORE_OBJ_STD_LEVEL },
        { "Domli the Humble", 30000, 116, player_race_type::DWARF, STORE_OBJ_STD_LEVEL },
        { "Yaarjukka Demonspawn", 30000, 111, player_race_type::IMP, STORE_OBJ_STD_LEVEL },
        { "Gelaraldor the Herbmaster", 30000, 111, player_race_type::HIGH_ELF, STORE_OBJ_STD_LEVEL },
        { "Olelaldan the Wise", 30000, 110, player_race_type::BARBARIAN, STORE_OBJ_STD_LEVEL },
        { "Fthoglo the Demonicist", 30000, 116, player_race_type::IMP, STORE_OBJ_STD_LEVEL },
        { "Dridash the Alchemist", 30000, 111, player_race_type::HALF_ORC, STORE_OBJ_STD_LEVEL },
        { "Nelir the Strong", 30000, 111, player_race_type::CYCLOPS, STORE_OBJ_STD_LEVEL },
        { "Lignus the Pungent", 30000, 110, player_race_type::HALF_ORC, STORE_OBJ_STD_LEVEL },
        { "Tilba", 30000, 116, player_race_type::HOBBIT, STORE_OBJ_STD_LEVEL },
        { "Myrildric the Wealthy", 30000, 111, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },

        { "Mauser the Chemist", 30000, 111, player_race_type::HALF_ELF, STORE_OBJ_STD_LEVEL },
        { "Wizzle the Chaotic", 30000, 110, player_race_type::HOBBIT, STORE_OBJ_STD_LEVEL },
        { "Midas the Greedy", 30000, 116, player_race_type::GNOME, STORE_OBJ_STD_LEVEL },
        { "Ja-Far the Alchemist", 30000, 111, player_race_type::ELF, STORE_OBJ_STD_LEVEL },
        { "Kakalrakakal", 30000, 116, player_race_type::KLACKON, STORE_OBJ_STD_LEVEL },
        { "Jal-Eth the Alchemist", 30000, 111, player_race_type::ELF, STORE_OBJ_STD_LEVEL },
#endif
    },

    {
/* Magic Shop - 23 unique names */
#ifdef JP
        { "ソーサラーのロ=パン", 30000, 110, player_race_type::HALF_ELF, STORE_OBJ_STD_LEVEL },
        { "偉大なるブガービイ", 30000, 113, player_race_type::GNOME, STORE_OBJ_STD_LEVEL },
        { "イェンダーの魔法使い", 30000, 110, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "死霊使いリャク", 30000, 110, player_race_type::HIGH_ELF, STORE_OBJ_STD_LEVEL },
        { "魔術師スキドゥニー", 30000, 110, player_race_type::HALF_ELF, STORE_OBJ_STD_LEVEL },
        { "幻術師キリア", 30000, 110, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "死霊術師ニッキ", 30000, 110, player_race_type::DARK_ELF, STORE_OBJ_STD_LEVEL },
        { "ソロストラン", 30000, 110, player_race_type::SPRITE, STORE_OBJ_STD_LEVEL },
        { "烏賊口アチシェ", 30000, 113, player_race_type::MIND_FLAYER, STORE_OBJ_STD_LEVEL },
        { "貴族のカザ", 30000, 110, player_race_type::HIGH_ELF, STORE_OBJ_STD_LEVEL },
        { "暗きファジル", 30000, 110, player_race_type::DARK_ELF, STORE_OBJ_STD_LEVEL },
        { "偉大なるケルドーン", 30000, 110, player_race_type::DWARF, STORE_OBJ_STD_LEVEL },
        { "フィランスロプス", 30000, 113, player_race_type::HOBBIT, STORE_OBJ_STD_LEVEL },
        { "魔女のアグナー", 30000, 110, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "死霊術師ビュリアンス", 30000, 110, player_race_type::BEASTMAN, STORE_OBJ_STD_LEVEL },
        { "ハイメイジのヴイラク", 30000, 110, player_race_type::BEASTMAN, STORE_OBJ_STD_LEVEL },
        { "知恵者マディッシュ", 30000, 113, player_race_type::BEASTMAN, STORE_OBJ_STD_LEVEL },
        { "ファレブリンボール", 30000, 110, player_race_type::HIGH_ELF, STORE_OBJ_STD_LEVEL },
        { "陰険フェリル=ガンド", 30000, 110, player_race_type::DARK_ELF, STORE_OBJ_STD_LEVEL },
        { "呪術師サレゴード", 30000, 110, player_race_type::BARBARIAN, STORE_OBJ_STD_LEVEL },
        { "神秘家クトゥアロス", 30000, 113, player_race_type::MIND_FLAYER, STORE_OBJ_STD_LEVEL },
        { "幻術師イベリ", 30000, 110, player_race_type::SKELETON, STORE_OBJ_STD_LEVEL },
        { "死霊術師ヘトー", 30000, 110, player_race_type::YEEK, STORE_OBJ_STD_LEVEL },
        { "魔術師ロ=パン", 30000, 110, player_race_type::HALF_ELF, STORE_OBJ_STD_LEVEL },
        { "偉大なるブガービイ", 30000, 113, player_race_type::GNOME, STORE_OBJ_STD_LEVEL },
        { "イェンダーの魔法使い", 30000, 110, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "死霊術師リャク", 30000, 110, player_race_type::DARK_ELF, STORE_OBJ_STD_LEVEL },
        { "魔術師スキドゥニー", 30000, 110, player_race_type::HALF_ELF, STORE_OBJ_STD_LEVEL },
        { "幻術師キリア", 30000, 110, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "死霊術師ニッキ", 30000, 110, player_race_type::DARK_ELF, STORE_OBJ_STD_LEVEL },
        { "ソロストラン", 30000, 110, player_race_type::SPRITE, STORE_OBJ_STD_LEVEL },
        { "烏賊口アチシェ", 30000, 113, player_race_type::MIND_FLAYER, STORE_OBJ_STD_LEVEL },
#else
        { "Lo Pan the Sorcerer", 30000, 110, player_race_type::HALF_ELF, STORE_OBJ_STD_LEVEL },
        { "Buggerby the Great", 30000, 113, player_race_type::GNOME, STORE_OBJ_STD_LEVEL },
        { "The Wizard of Yendor", 30000, 110, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "Rjak the Necromancer", 30000, 110, player_race_type::DARK_ELF, STORE_OBJ_STD_LEVEL },
        { "Skidney the Sorcerer", 30000, 110, player_race_type::HALF_ELF, STORE_OBJ_STD_LEVEL },
        { "Kyria the Illusionist", 30000, 110, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "Nikki the Necromancer", 30000, 110, player_race_type::DARK_ELF, STORE_OBJ_STD_LEVEL },
        { "Solostoran", 30000, 110, player_race_type::SPRITE, STORE_OBJ_STD_LEVEL },
        { "Achshe the Tentacled", 30000, 113, player_race_type::MIND_FLAYER, STORE_OBJ_STD_LEVEL },
        { "Kaza the Noble", 30000, 110, player_race_type::HIGH_ELF, STORE_OBJ_STD_LEVEL },
        { "Fazzil the Dark", 30000, 110, player_race_type::DARK_ELF, STORE_OBJ_STD_LEVEL },
        { "Keldorn the Grand", 30000, 110, player_race_type::DWARF, STORE_OBJ_STD_LEVEL },
        { "Philanthropus", 30000, 113, player_race_type::HOBBIT, STORE_OBJ_STD_LEVEL },
        { "Agnar the Enchantress", 30000, 110, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "Buliance the Necromancer", 30000, 110, player_race_type::BEASTMAN, STORE_OBJ_STD_LEVEL },
        { "Vuirak the High-Mage", 30000, 110, player_race_type::BEASTMAN, STORE_OBJ_STD_LEVEL },
        { "Madish the Smart", 30000, 113, player_race_type::BEASTMAN, STORE_OBJ_STD_LEVEL },
        { "Falebrimbor", 30000, 110, player_race_type::HIGH_ELF, STORE_OBJ_STD_LEVEL },
        { "Felil-Gand the Subtle", 30000, 110, player_race_type::DARK_ELF, STORE_OBJ_STD_LEVEL },
        { "Thalegord the Shaman", 30000, 110, player_race_type::BARBARIAN, STORE_OBJ_STD_LEVEL },
        { "Cthoaloth the Mystic", 30000, 113, player_race_type::MIND_FLAYER, STORE_OBJ_STD_LEVEL },
        { "Ibeli the Illusionist", 30000, 110, player_race_type::SKELETON, STORE_OBJ_STD_LEVEL },
        { "Heto the Necromancer", 30000, 110, player_race_type::YEEK, STORE_OBJ_STD_LEVEL },
        { "Lo Pan the Sorcerer", 30000, 110, player_race_type::HALF_ELF, STORE_OBJ_STD_LEVEL },
        { "Buggerby the Great", 30000, 113, player_race_type::GNOME, STORE_OBJ_STD_LEVEL },
        { "The Wizard of Yendor", 30000, 110, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "Rjak the Necromancer", 30000, 110, player_race_type::DARK_ELF, STORE_OBJ_STD_LEVEL },
        { "Skidney the Sorcerer", 30000, 110, player_race_type::HALF_ELF, STORE_OBJ_STD_LEVEL },
        { "Kyria the Illusionist", 30000, 110, player_race_type::HUMAN, STORE_OBJ_STD_LEVEL },
        { "Nikki the Necromancer", 30000, 110, player_race_type::DARK_ELF, STORE_OBJ_STD_LEVEL },
        { "Solostoran", 30000, 110, player_race_type::SPRITE, STORE_OBJ_STD_LEVEL },
        { "Achshe the Tentacled", 30000, 113, player_race_type::MIND_FLAYER, STORE_OBJ_STD_LEVEL },
#endif

    }
};
