#pragma once
#include "util/flag-group.h"

enum spells_type
{
	AttributeType::NONE = 0,
	AttributeType::ELEC = 1,				/*!< 魔法効果: 電撃*/
	AttributeType::POIS = 2,				/*!< 魔法効果: 毒*/
	AttributeType::ACID = 3,				/*!< 魔法効果: 酸*/
	AttributeType::COLD = 4,				/*!< 魔法効果: 冷気*/
	AttributeType::FIRE = 5,				/*!< 魔法効果: 火炎*/
	AttributeType::PSY_SPEAR = 9,			/*!< 魔法効果: 光の剣*/
	AttributeType::MISSILE = 10,			/*!< 魔法効果: 弱魔力*/
	AttributeType::ARROW = 11,				/*!< 魔法効果: 射撃*/
	AttributeType::PLASMA = 12,				/*!< 魔法効果: プラズマ*/
	AttributeType::WATER = 14,				/*!< 魔法効果: 水流*/
	AttributeType::LITE = 15,				/*!< 魔法効果: 閃光*/
	AttributeType::DARK = 16,				/*!< 魔法効果: 暗黒*/
	AttributeType::LITE_WEAK = 17,			/*!< 魔法効果: 弱光*/
	AttributeType::DARK_WEAK = 18,			/*!< 魔法効果: 弱暗*/
	AttributeType::SHARDS = 20,				/*!< 魔法効果: 破片*/
	AttributeType::SOUND = 21,				/*!< 魔法効果: 轟音*/
	AttributeType::CONFUSION = 22,			/*!< 魔法効果: 混乱*/
	AttributeType::FORCE = 23,				/*!< 魔法効果: フォース*/
	AttributeType::INERTIAL = 24,			/*!< 魔法効果: 遅鈍*/
	AttributeType::MANA = 26,				/*!< 魔法効果: 純粋魔力*/
	AttributeType::METEOR = 27,				/*!< 魔法効果: 隕石*/
	AttributeType::ICE = 28,				/*!< 魔法効果: 極寒*/
	AttributeType::CHAOS = 30,				/*!< 魔法効果: カオス*/
	AttributeType::NETHER = 31,				/*!< 魔法効果: 地獄*/
	AttributeType::DISENCHANT = 32,			/*!< 魔法効果: 劣化*/
	AttributeType::NEXUS = 33,				/*!< 魔法効果: 因果混乱*/
	AttributeType::TIME = 34,				/*!< 魔法効果: 時間逆転*/
	AttributeType::GRAVITY = 35,			/*!< 魔法効果: 重力*/
	AttributeType::KILL_WALL = 40,			/*!< 魔法効果: 岩石溶解*/
	AttributeType::KILL_DOOR = 41,			/*!< 魔法効果: ドア破壊*/
	AttributeType::KILL_TRAP = 42,			/*!< 魔法効果: トラップ破壊*/
	AttributeType::MAKE_WALL = 45,			/*!< 魔法効果: 壁生成*/
	AttributeType::MAKE_DOOR = 46,			/*!< 魔法効果: ドア生成*/
	AttributeType::MAKE_TRAP = 47,			/*!< 魔法効果: トラップ生成*/
	AttributeType::MAKE_TREE = 48,			/*!< 魔法効果: 森林生成*/
	AttributeType::OLD_CLONE = 51,			/*!< 魔法効果: クローン・モンスター*/
	AttributeType::OLD_POLY = 52,			/*!< 魔法効果: チェンジ・モンスター*/
	AttributeType::OLD_HEAL = 53,			/*!< 魔法効果: 回復モンスター*/
	AttributeType::OLD_SPEED = 54,			/*!< 魔法効果: スピード・モンスター*/
	AttributeType::OLD_SLOW = 55,			/*!< 魔法効果: スロウ・モンスター*/
	AttributeType::OLD_CONF = 56,			/*!< 魔法効果: パニック・モンスター*/
	AttributeType::OLD_SLEEP = 57,			/*!< 魔法効果: スリープ・モンスター*/
	AttributeType::HYPODYNAMIA = 58,		/*!< 魔法効果: 衰弱*/
	AttributeType::AWAY_UNDEAD = 61,		/*!< 魔法効果: アンデッド・アウェイ*/
	AttributeType::AWAY_EVIL = 62,			/*!< 魔法効果: 邪悪飛ばし*/
	AttributeType::AWAY_ALL = 63,			/*!< 魔法効果: テレポート・アウェイ*/
	AttributeType::TURN_UNDEAD = 64,		/*!< 魔法効果: アンデッド恐慌*/
	AttributeType::TURN_EVIL = 65,			/*!< 魔法効果: 邪悪恐慌*/
	AttributeType::TURN_ALL = 66,			/*!< 魔法効果: モンスター恐慌*/
	AttributeType::DISP_UNDEAD = 67,		/*!< 魔法効果: アンデッド退散*/
	AttributeType::DISP_EVIL = 68,			/*!< 魔法効果: 邪悪退散*/
	AttributeType::DISP_ALL = 69,			/*!< 魔法効果: モンスター退散*/
	AttributeType::DISP_DEMON = 70,			/*!< 魔法効果: 悪魔退散*/
	AttributeType::DISP_LIVING = 71,		/*!< 魔法効果: 生命退散*/
	AttributeType::ROCKET = 72,				/*!< 魔法効果: ロケット*/
	AttributeType::NUKE = 73,				/*!< 魔法効果: 放射性廃棄物*/
	AttributeType::MAKE_RUNE_PROTECTION = 74,  /*!< 魔法効果: 守りのルーン生成*/
	AttributeType::STASIS = 75,				/*!< 魔法効果: モンスター拘束*/
	AttributeType::STONE_WALL = 76,			/*!< 魔法効果: 壁生成*/
	AttributeType::DEATH_RAY = 77,			/*!< 魔法効果: 死の光線*/
	AttributeType::STUN = 78,				/*!< 魔法効果: 朦朧*/
	AttributeType::HOLY_FIRE = 79,			/*!< 魔法効果: 聖光*/
	AttributeType::HELL_FIRE = 80,			/*!< 魔法効果: 地獄の劫火*/
	AttributeType::DISINTEGRATE = 81,		/*!< 魔法効果: 分解*/
	AttributeType::CHARM = 82,				/*!< 魔法効果: モンスター魅了*/
	AttributeType::CONTROL_UNDEAD = 83,		/*!< 魔法効果: アンデッド支配*/
	AttributeType::CONTROL_ANIMAL = 84,		/*!< 魔法効果: 動物支配*/
	AttributeType::PSI = 85,				/*!< 魔法効果: サイキック攻撃*/
	AttributeType::PSI_DRAIN = 86,			/*!< 魔法効果: 精神吸収*/
	AttributeType::TELEKINESIS = 87,		/*!< 魔法効果: テレキシネス*/
	AttributeType::JAM_DOOR = 88,			/*!< 魔法効果: 施錠*/
	AttributeType::DOMINATION = 89,			/*!< 魔法効果: 精神支配*/
	AttributeType::DISP_GOOD = 90,			/*!< 魔法効果: 善良退散*/
	AttributeType::DRAIN_MANA = 91,			/*!< 魔法効果: 魔力吸収*/
	AttributeType::MIND_BLAST = 92,			/*!< 魔法効果: 精神攻撃*/
	AttributeType::BRAIN_SMASH = 93,		/*!< 魔法効果: 脳攻撃*/
	AttributeType::CAUSE_1 = 94,			/*!< 魔法効果: 軽傷の呪い*/
	AttributeType::CAUSE_2 = 95,			/*!< 魔法効果: 重傷の呪い*/
	AttributeType::CAUSE_3 = 96,			/*!< 魔法効果: 致命傷の呪い*/
	AttributeType::CAUSE_4 = 97,			/*!< 魔法効果: 秘孔を突く*/
	AttributeType::HAND_DOOM = 98,			/*!< 魔法効果: 破滅の手*/
	AttributeType::CAPTURE = 99,			/*!< 魔法効果: 捕縛*/
	AttributeType::ANIM_DEAD = 100,			/*!< 魔法効果: 死者復活*/
	AttributeType::CHARM_LIVING = 101,		/*!< 魔法効果: 生命魅了*/
	AttributeType::IDENTIFY = 102,			/*!< 魔法効果: 鑑定*/
	AttributeType::ATTACK = 103,			/*!< 魔法効果: 白兵*/
	AttributeType::ENGETSU = 104,			/*!< 魔法効果: 円月*/
	AttributeType::GENOCIDE = 105,			/*!< 魔法効果: 抹殺*/
	AttributeType::PHOTO = 106,				/*!< 魔法効果: 撮影*/
	AttributeType::CONTROL_DEMON = 107,		/*!< 魔法効果: 悪魔支配*/
	AttributeType::LAVA_FLOW = 108,			/*!< 魔法効果: 溶岩噴出*/
	AttributeType::BLOOD_CURSE = 109,		/*!< 魔法効果: 血の呪い*/
	AttributeType::SEEKER = 110,			/*!< 魔法効果: シーカーレイ*/
	AttributeType::SUPER_RAY = 111,			/*!< 魔法効果: スーパーレイ*/
	AttributeType::STAR_HEAL = 112,			/*!< 魔法効果: 星の癒し*/
	AttributeType::WATER_FLOW = 113,		/*!< 魔法効果: 流水*/
	AttributeType::CRUSADE = 114,			/*!< 魔法効果: 聖戦*/
	AttributeType::STASIS_EVIL = 115,		/*!< 魔法効果: 邪悪拘束*/
	AttributeType::WOUNDS = 116,			/*!< 魔法効果: 創傷*/
    AttributeType::E_GENOCIDE = 117,		/*!< 魔法効果: 元素抹殺 */
	AttributeType::VOID = 118,              /*!< 魔法効果: 虚無 */
	AttributeType::ABYSS = 119,             /*!< 魔法効果: 深淵 */
    AttributeType::DIRT = 120,			/*!< 魔法効果: 汚物 */
    AttributeType::STUNGUN = 121, /*!< 魔法効果: スタンガン */
    AttributeType::HUNGRY = 122,            /*!< 魔法効果: 空腹>*/
    AttributeType::PLAYER_SHOOT = 123,		/*!< 属性取得用: プレイヤーの射撃/投擲>*/
	AttributeType::PLAYER_MELEE = 124,		 /*!< 属性取得用: プレイヤーの近接攻撃>*/
	MAX_GF = 125,		        /*!< 欠番を無視した最大サイズ (直上の値+1) */
};


/*! 属性フラグspell_typesの集合を表すクラス */
using EffectFlags = FlagGroup<spells_type, MAX_GF>;
