#include "info-reader/feature-info-tokens-table.h"

/*!
 * @brief 地形属性トークンの定義 / Feature info flags
 */
const std::unordered_map<std::string_view, FloorFeatureType> f_info_flags = {
    { "LOS", FloorFeatureType::LOS },
    { "PROJECT", FloorFeatureType::PROJECT },
    { "MOVE", FloorFeatureType::MOVE },
    { "PLACE", FloorFeatureType::PLACE },
    { "DROP", FloorFeatureType::DROP },
    { "SECRET", FloorFeatureType::SECRET },
    { "NOTICE", FloorFeatureType::NOTICE },
    { "REMEMBER", FloorFeatureType::REMEMBER },
    { "OPEN", FloorFeatureType::OPEN },
    { "CLOSE", FloorFeatureType::CLOSE },
    { "BASH", FloorFeatureType::BASH },
    { "SPIKE", FloorFeatureType::SPIKE },
    { "DISARM", FloorFeatureType::DISARM },
    { "STORE", FloorFeatureType::STORE },
    { "TUNNEL", FloorFeatureType::TUNNEL },
    { "MAY_HAVE_GOLD", FloorFeatureType::MAY_HAVE_GOLD },
    { "HAS_GOLD", FloorFeatureType::HAS_GOLD },
    { "HAS_ITEM", FloorFeatureType::HAS_ITEM },
    { "DOOR", FloorFeatureType::DOOR },
    { "TRAP", FloorFeatureType::TRAP },
    { "STAIRS", FloorFeatureType::STAIRS },
    { "RUNE_PROTECTION", FloorFeatureType::RUNE_PROTECTION },
    { "LESS", FloorFeatureType::LESS },
    { "MORE", FloorFeatureType::MORE },
    { "AVOID_RUN", FloorFeatureType::AVOID_RUN },
    { "FLOOR", FloorFeatureType::FLOOR },
    { "WALL", FloorFeatureType::WALL },
    { "PERMANENT", FloorFeatureType::PERMANENT },
    { "CHAOS_TAINTED", FloorFeatureType::CHAOS_TAINTED },
    { "VOID", FloorFeatureType::VOID },
    // { "XXX00", FloorFeatureType::XXX00 },
    // { "XXX01", FloorFeatureType::XXX01 },
    // { "XXX02", FloorFeatureType::XXX02 },
    { "HIT_TRAP", FloorFeatureType::HIT_TRAP },

    // { "BRIDGE", FloorFeatureType::BRIDGE },
    // { "RIVER", FloorFeatureType::RIVER },
    // { "LAKE", FloorFeatureType::LAKE },
    // { "BRIDGED", FloorFeatureType::BRIDGED },
    // { "COVERED", FloorFeatureType::COVERED },
    { "GLOW", FloorFeatureType::GLOW },
    { "ENSECRET", FloorFeatureType::ENSECRET },
    { "WATER", FloorFeatureType::WATER },
    { "LAVA", FloorFeatureType::LAVA },
    { "SHALLOW", FloorFeatureType::SHALLOW },
    { "DEEP", FloorFeatureType::DEEP },
    { "POISON_PUDDLE", FloorFeatureType::POISON_PUDDLE },
    { "HURT_ROCK", FloorFeatureType::HURT_ROCK },
    // { "HURT_FIRE", FloorFeatureType::HURT_FIRE },
    // { "HURT_COLD", FloorFeatureType::HURT_COLD },
    // { "HURT_ACID", FloorFeatureType::HURT_ACID },
    { "COLD_PUDDLE", FloorFeatureType::COLD_PUDDLE },
    { "ACID_PUDDLE", FloorFeatureType::ACID_PUDDLE },
    // { "OIL", FloorFeatureType::OIL },
    { "ELEC_PUDDLE", FloorFeatureType::ELEC_PUDDLE },
    // { "CAN_CLIMB", FloorFeatureType::CAN_CLIMB },
    { "CAN_FLY", FloorFeatureType::CAN_FLY },
    { "CAN_SWIM", FloorFeatureType::CAN_SWIM },
    { "CAN_PASS", FloorFeatureType::CAN_PASS },
    // { "CAN_OOZE", FloorFeatureType::CAN_OOZE },
    { "CAN_DIG", FloorFeatureType::CAN_DIG },
    // { "HIDE_ITEM", FloorFeatureType::HIDE_ITEM },
    // { "HIDE_SNEAK", FloorFeatureType::HIDE_SNEAK },
    // { "HIDE_SWIM", FloorFeatureType::HIDE_SWIM },
    // { "HIDE_DIG", FloorFeatureType::HIDE_DIG },
    // { "KILL_HUGE", FloorFeatureType::KILL_HUGE },
    // { "KILL_MOVE", FloorFeatureType::KILL_MOVE },

    // { "PICK_TRAP", FloorFeatureType::PICK_TRAP },
    // { "PICK_DOOR", FloorFeatureType::PICK_DOOR },
    // { "ALLOC", FloorFeatureType::ALLOC },
    // { "CHEST", FloorFeatureType::CHEST },
    // { "DROP_1D2", FloorFeatureType::DROP_1D2 },
    // { "DROP_2D2", FloorFeatureType::DROP_2D2 },
    // { "DROP_GOOD", FloorFeatureType::DROP_GOOD },
    // { "DROP_GREAT", FloorFeatureType::DROP_GREAT },
    // { "HURT_POIS", FloorFeatureType::HURT_POIS },
    // { "HURT_ELEC", FloorFeatureType::HURT_ELEC },
    // { "HURT_WATER", FloorFeatureType::HURT_WATER },
    // { "HURT_BWATER", FloorFeatureType::HURT_BWATER },
    // { "USE_FEAT", FloorFeatureType::USE_FEAT },
    // { "GET_FEAT", FloorFeatureType::GET_FEAT },
    // { "GROUND", FloorFeatureType::GROUND },
    // { "OUTSIDE", FloorFeatureType::OUTSIDE },
    // { "EASY_HIDE", FloorFeatureType::EASY_HIDE },
    // { "EASY_CLIMB", FloorFeatureType::EASY_CLIMB },
    // { "MUST_CLIMB", FloorFeatureType::MUST_CLIMB },
    { "TREE", FloorFeatureType::TREE },
    // { "NEED_TREE", FloorFeatureType::NEED_TREE },
    // { "BLOOD", FloorFeatureType::BLOOD },
    // { "DUST", FloorFeatureType::DUST },
    // { "SLIME", FloorFeatureType::SLIME },
    { "PLANT", FloorFeatureType::PLANT },
    // { "XXX2", FloorFeatureType::XXX2 },
    // { "INSTANT", FloorFeatureType::INSTANT },
    // { "EXPLODE", FloorFeatureType::EXPLODE },
    // { "TIMED", FloorFeatureType::TIMED },
    // { "ERUPT", FloorFeatureType::ERUPT },
    // { "STRIKE", FloorFeatureType::STRIKE },
    // { "SPREAD", FloorFeatureType::SPREAD },

    { "SPECIAL", FloorFeatureType::SPECIAL },
    { "HURT_DISI", FloorFeatureType::HURT_DISI },
    { "QUEST_ENTER", FloorFeatureType::QUEST_ENTER },
    { "QUEST_EXIT", FloorFeatureType::QUEST_EXIT },
    { "QUEST", FloorFeatureType::QUEST },
    { "SHAFT", FloorFeatureType::SHAFT },
    { "MOUNTAIN", FloorFeatureType::MOUNTAIN },
    { "BLDG", FloorFeatureType::BLDG },
    { "RUNE_EXPLOSION", FloorFeatureType::RUNE_EXPLOSION },
    { "PATTERN", FloorFeatureType::PATTERN },
    { "TOWN", FloorFeatureType::TOWN },
    { "ENTRANCE", FloorFeatureType::ENTRANCE },
    { "MIRROR", FloorFeatureType::MIRROR },
    { "UNPERM", FloorFeatureType::UNPERM },
    { "TELEPORTABLE", FloorFeatureType::TELEPORTABLE },
    { "CONVERT", FloorFeatureType::CONVERT },
    { "GLASS", FloorFeatureType::GLASS },
    { "DUNG_POOL", FloorFeatureType::DUNG_POOL },
    { "PLASMA", FloorFeatureType::PLASMA },
    { "RUNE_HEALING", FloorFeatureType::RUNE_HEALING },
    { "SLOW", FloorFeatureType::SLOW },
    { "THORN", FloorFeatureType::THORN },
    { "TENTACLE", FloorFeatureType::TENTACLE },

};
