#pragma once

enum class MonsterMiscType {
    FORCE_DEPTH = 0,
    FORCE_MAXHP = 1,
    HAS_FRIENDS = 2,
    ESCORT = 3,
    MORE_ESCORT = 4,
    RIDING = 5,
    INVISIBLE = 6,
    COLD_BLOOD = 7,
    KAGE = 8,
    CHAMELEON = 9,
    TANUKI = 10,
    NO_QUEST = 11,
    ELDRITCH_HORROR = 12,
    MULTIPLY = 13,
    REGENERATE = 14,
    POWERFUL = 15,
    REFLECTING = 16,
    QUESTOR = 17,
    EMPTY_MIND = 18,
    WEIRD_MIND = 19,
    GUARDIAN = 20,
    VOCIFEROUS = 21,
    FORCE_EXTRA = 22,
    FRIENDS = 23,
    ESCORTS = 24,
    CHAR_MULTI = 25,
    XX15 = 26,
    MAX
};

enum class MonsterFeedType {
    BLIND = 1,
    CONF = 2,
    MANA = 3,
    NEXUS = 4,
    SLEEP = 5,
    BERSERKER = 6,
    ACIDIC = 7,
    SPEED = 8,
    CURE = 9,
    FIRE_RES = 10,
    COLD_RES = 11,
    ACID_RES = 12,
    ELEC_RES = 13,
    POIS_RES = 14,
    INSANITY = 15,
    DRAIN_EXP = 16,
    POISONOUS = 17,
    GIVE_STR = 18,
    GIVE_INT = 19,
    GIVE_WIS = 20,
    GIVE_DEX = 21,
    GIVE_CON = 22,
    GIVE_CHR = 23,
    LOSE_STR = 24,
    LOSE_INT = 25,
    LOSE_WIS = 26,
    LOSE_DEX = 27,
    LOSE_CON = 28,
    LOSE_CHR = 29,
    DRAIN_MANA = 30,
    MAX
};
