#pragma once

enum class MonsterKindType {
    UNIQUE = 0,
    NONLIVING = 1,
    HUMAN = 2,
    QUANTUM = 3,
    ORC = 4,
    TROLL = 5,
    GIANT = 6,
    DRAGON = 7,
    DEMON = 8,
    AMBERITE = 9,
    ANGEL = 10,
    EVIL = 11,
    GOOD = 12,
    ANIMAL = 13,
    UNDEAD = 14,
    ELDRAZI = 15,
    ELF = 16,
    DWARF = 17,
    HOBBIT = 18,
    QUYLTHLUG = 19,
    SPIDER = 20,
    NASTY = 21,
    JOKE = 22,
    YAKUZA = 23,
    NINJA = 24,
    SUMOU_WRESTLER = 25,
    WARRIOR = 26,
    ROGUE = 27,
    MAGE = 28,
    PRIEST = 29,
    PALADIN = 30,
    RANGER = 31,
    SAMURAI = 32,
    KARATEKA = 33,
    HOMO_SEXUAL = 34,
    TANK = 35,
    HENTAI = 36,
    ELEMENTAL = 37,
    GOLEM = 38,
    PUYO = 39,
    MAX,
};
