/*!
 * @brief Index of spell type names
 */

#include "gf-descriptions.h"
#include "spell/spell-types.h"

const named_num gf_desc[MAX_NAMED_NUM] =
{
	{"AttributeType::ELEC", 				AttributeType::ELEC				},
	{"AttributeType::POIS", 				AttributeType::POIS				},
	{"AttributeType::ACID", 				AttributeType::ACID				},
	{"AttributeType::COLD", 				AttributeType::COLD				},
	{"AttributeType::FIRE",		 			AttributeType::FIRE				},
	{"AttributeType::PSY_SPEAR",			AttributeType::PSY_SPEAR		},
	{"AttributeType::MISSILE",				AttributeType::MISSILE			},
	{"AttributeType::ARROW",				AttributeType::ARROW			},
	{"AttributeType::PLASMA",				AttributeType::PLASMA			},
	{"AttributeType::WATER",				AttributeType::WATER			},
	{"AttributeType::LITE",					AttributeType::LITE				},
	{"AttributeType::DARK",					AttributeType::DARK				},
	{"AttributeType::LITE_WEAK",			AttributeType::LITE_WEAK		},
	{"AttributeType::DARK_WEAK",			AttributeType::DARK_WEAK		},
	{"AttributeType::SHARDS",				AttributeType::SHARDS			},
	{"AttributeType::SOUND",				AttributeType::SOUND			},
	{"AttributeType::CONFUSION",			AttributeType::CONFUSION		},
	{"AttributeType::FORCE",				AttributeType::FORCE			},
	{"AttributeType::INERTIA",				AttributeType::INERTIAL			},
	{"AttributeType::MANA",					AttributeType::MANA				},
	{"AttributeType::METEOR",				AttributeType::METEOR			},
	{"AttributeType::ICE",					AttributeType::ICE				},
	{"AttributeType::CHAOS",				AttributeType::CHAOS			},
	{"AttributeType::NETHER",				AttributeType::NETHER			},
	{"AttributeType::DISENCHANT",			AttributeType::DISENCHANT		},
	{"AttributeType::NEXUS",				AttributeType::NEXUS			},
	{"AttributeType::TIME",					AttributeType::TIME				},
	{"AttributeType::GRAVITY",				AttributeType::GRAVITY			},
	{"AttributeType::KILL_WALL",			AttributeType::KILL_WALL		},
	{"AttributeType::KILL_DOOR",			AttributeType::KILL_DOOR		},
	{"AttributeType::KILL_TRAP",			AttributeType::KILL_TRAP		},
	{"AttributeType::MAKE_WALL",			AttributeType::MAKE_WALL		},
	{"AttributeType::MAKE_DOOR",			AttributeType::MAKE_DOOR		},
	{"AttributeType::MAKE_TRAP",			AttributeType::MAKE_TRAP		},
	{"AttributeType::MAKE_TREE",			AttributeType::MAKE_TREE		},
	{"AttributeType::OLD_CLONE",			AttributeType::OLD_CLONE		},
	{"AttributeType::OLD_POLY",				AttributeType::OLD_POLY			},
	{"AttributeType::OLD_HEAL",				AttributeType::OLD_HEAL			},
	{"AttributeType::OLD_SPEED",			AttributeType::OLD_SPEED		},
	{"AttributeType::OLD_SLOW",				AttributeType::OLD_SLOW			},
	{"AttributeType::OLD_CONF",				AttributeType::OLD_CONF			},
	{"AttributeType::OLD_SLEEP",			AttributeType::OLD_SLEEP		},
	{"AttributeType::HYPODYNAMIA",			AttributeType::HYPODYNAMIA		},
	{"AttributeType::AWAY_UNDEAD",			AttributeType::AWAY_UNDEAD		},
	{"AttributeType::AWAY_EVIL",			AttributeType::AWAY_EVIL		},
	{"AttributeType::AWAY_ALL",				AttributeType::AWAY_ALL			},
	{"AttributeType::TURN_UNDEAD",			AttributeType::TURN_UNDEAD		},
	{"AttributeType::TURN_EVIL",			AttributeType::TURN_EVIL		},
	{"AttributeType::TURN_ALL",				AttributeType::TURN_ALL			},
	{"AttributeType::DISP_UNDEAD",			AttributeType::DISP_UNDEAD		},
	{"AttributeType::DISP_EVIL",			AttributeType::DISP_EVIL		},
	{"AttributeType::DISP_ALL",				AttributeType::DISP_ALL			},
	{"AttributeType::DISP_DEMON",			AttributeType::DISP_DEMON		},
	{"AttributeType::DISP_LIVING",			AttributeType::DISP_LIVING		},
	{"AttributeType::ROCKET",				AttributeType::ROCKET			},
	{"AttributeType::NUKE",					AttributeType::NUKE				},
    {"AttributeType::MAKE_RUNE_PROTECTION",	AttributeType::MAKE_RUNE_PROTECTION},
	{"AttributeType::STASIS",				AttributeType::STASIS			},
	{"AttributeType::STONE_WALL",			AttributeType::STONE_WALL		},
	{"AttributeType::DEATH_RAY",			AttributeType::DEATH_RAY		},
	{"AttributeType::STUN",					AttributeType::STUN				},
	{"AttributeType::HOLY_FIRE",			AttributeType::HOLY_FIRE		},
	{"AttributeType::HELL_FIRE",			AttributeType::HELL_FIRE		},
	{"AttributeType::DISINTEGRATE",			AttributeType::DISINTEGRATE		},
	{"AttributeType::CHARM",				AttributeType::CHARM			},
	{"AttributeType::CONTROL_UNDEAD",		AttributeType::CONTROL_UNDEAD	},
	{"AttributeType::CONTROL_ANIMAL",		AttributeType::CONTROL_ANIMAL	},
	{"AttributeType::PSI",					AttributeType::PSI				},
	{"AttributeType::PSI_DRAIN",			AttributeType::PSI_DRAIN		},
	{"AttributeType::TELEKINESIS",			AttributeType::TELEKINESIS		},
	{"AttributeType::JAM_DOOR",				AttributeType::JAM_DOOR			},
	{"AttributeType::DOMINATION",			AttributeType::DOMINATION		},
	{"AttributeType::DISP_GOOD",			AttributeType::DISP_GOOD		},
	{"AttributeType::DRAIN_MANA",			AttributeType::DRAIN_MANA		},
	{"AttributeType::MIND_BLAST",			AttributeType::MIND_BLAST		},
	{"AttributeType::BRAIN_SMASH",			AttributeType::BRAIN_SMASH		},
	{"AttributeType::CAUSE_1",				AttributeType::CAUSE_1			},
	{"AttributeType::CAUSE_2",				AttributeType::CAUSE_2			},
	{"AttributeType::CAUSE_3",				AttributeType::CAUSE_3			},
	{"AttributeType::CAUSE_4",				AttributeType::CAUSE_4			},
	{"AttributeType::HAND_DOOM",			AttributeType::HAND_DOOM		},
	{"AttributeType::CAPTURE",				AttributeType::CAPTURE			},
	{"AttributeType::ANIM_DEAD",			AttributeType::ANIM_DEAD		},
	{"AttributeType::CHARM_LIVING",			AttributeType::CHARM_LIVING		},
	{"AttributeType::IDENTIFY",				AttributeType::IDENTIFY			},
	{"AttributeType::ATTACK",				AttributeType::ATTACK			},
	{"AttributeType::ENGETSU",				AttributeType::ENGETSU			},
	{"AttributeType::GENOCIDE",				AttributeType::GENOCIDE			},
	{"AttributeType::PHOTO",				AttributeType::PHOTO			},
	{"AttributeType::CONTROL_DEMON",		AttributeType::CONTROL_DEMON	},
	{"AttributeType::LAVA_FLOW",			AttributeType::LAVA_FLOW		},
	{"AttributeType::BLOOD_CURSE",			AttributeType::BLOOD_CURSE		},
	{"AttributeType::SEEKER",				AttributeType::SEEKER			},
	{"AttributeType::SUPER_RAY",			AttributeType::SUPER_RAY		},
	{"AttributeType::STAR_HEAL",			AttributeType::STAR_HEAL		},
	{"AttributeType::WATER_FLOW",			AttributeType::WATER_FLOW		},
	{"AttributeType::CRUSADE",				AttributeType::CRUSADE			},
	{"AttributeType::STASIS_EVIL",			AttributeType::STASIS_EVIL		},
	{"AttributeType::WOUNDS",				AttributeType::WOUNDS			},
	{"AttributeType::E_GENOCIDE",           AttributeType::E_GENOCIDE       },
	{"AttributeType::VOID",                 AttributeType::VOID             },
	{"AttributeType::ABYSS",                AttributeType::ABYSS            },
	{"AttributeType::DIRT", 				AttributeType::DIRT				},
    {"AttributeType::HUNGRY",               AttributeType::HUNGRY           },
};
