name: Create Cache for ccache

on:
  push:
    branches:
      - develop

  # 手動トリガーを許可
  workflow_dispatch:

jobs:
  clang_without_pch_japanese:
    name: Japanese version with clang (without using pre-compiled headers)
    uses: ./.github/workflows/build-with-autotools.yml
    with:
      runner: ubuntu-22.04
      cxx: clang++-14
      cxx-flags: "-pipe -O3 -Werror -Wall -Wextra -Wno-unused-const-variable -Wno-invalid-source-encoding -stdlib=libc++"
      configure-opts: "--disable-pch"
      use-ccache: true

  gcc_japanese:
    name: Japanese version with gcc
    uses: ./.github/workflows/build-with-autotools.yml
    with:
      runner: ubuntu-24.04
      cxx: g++-13
      cxx-flags: "-pipe -O3 -Werror -Wall -Wextra"
      configure-opts: "--disable-pch"
      use-ccache: true

  gcc_english:
    name: English version with gcc
    uses: ./.github/workflows/build-with-autotools.yml
    with:
      runner: ubuntu-24.04
      cxx: g++-13
      cxx-flags: "-pipe -O3 -Werror -Wall -Wextra"
      configure-opts: "--disable-pch --disable-japanese"
      distcheck: true
      use-ccache: true
